name = "Manic"
filename = "Manic.zip"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/n382wpVP/versions/Eij8qoKG/manic-datapack.zip"
hash-format = "sha1"
hash = "04972acdf5078e80dd9b1308926fc8f8e94bde49"

[update]
[update.modrinth]
mod-id = "zliP2NTL"
version = "wNQcU0oY"
