on:
  release:
    types: [published]

concurrency:
  group: "build"
  cancel-in-progress: true

env:
  MODRINTH_ID: "1UPdBpGk"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Build Packs
        run: |
          bash build.sh ${{ github.event.release.tag_name }}

      - name: Publish
        uses: Kir-Antipov/mc-publish@master
        with:
          modrinth-id: "${{ env.MODRINTH_ID }}"
          modrinth-token: "${{ secrets.MODRINTH_TOKEN }}"
          modrinth-version-type: "${{ steps.get-release.outputs.release-type }}"
          github-tag: "${{ github.event.release.tag_name }}"
          github-token: ${{ secrets.GITHUB_TOKEN }}

          name: "The Theatre v${{ github.event.release.tag_name }}"
          version: "${{ github.event.release.tag_name }}"
          version-type: release
          loaders: fabric
          game-versions: |
            1.20.4
          java: 17
          files: |
            build/the-theatre.mrpack